language: java
jdk:
  - openjdk9
services:
  - mysql
cache:
   directories:
     - $HOME/.m2
before_install:
  - mysql -u root -e "create database hotelManagementDB";
  - mysql -u root -e "CREATE USER 'hm'@'%' IDENTIFIED BY 'hm'";
  - mysql -u root -e "GRANT ALL ON hotelManagementDB.* TO 'hm'@'%'";
  - rmiregistry -J-Djava.rmi.server.useCodebaseOnly=false %