language: java
jdk:
  - openjdk9
services:
  - mysql
cache:
   directories:
     - $HOME/.m2
before_install:
  - mysql -u root -e "create database hotelManagementDB";
  - mysql -u root hotelManagementDB < hotel-management.sql