/* DELETE 'hotelDB' database*/
DROP SCHEMA IF EXISTS hotelDB;
/* DELETE USER 'spq' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'%';

/* CREATE ''easyBookingDB' DATABASE */
CREATE SCHEMA hotelDB;
/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER IF NOT EXISTS 'spq'@'%' IDENTIFIED BY 'spq';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'spq' AT LOCAL SERVER*/
GRANT ALL ON hotelDB.* TO 'spq'@'%';